# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simi' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Simi
  pod 'GoogleSignIn'
  pod 'AppAuth', '0.95.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', 
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation', 
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end

