# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Simi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simi
  pod 'Firebase'
  pod 'GoogleSignIn'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'SimiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Simi-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simi-tvOS

  target 'Simi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end